import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import Providers from './providers';
import RecoilProvider from './RecoilProvider';
const inter = Plus_Jakarta_Sans({
  subsets: ['latin'],
  display: 'swap',
});
export const metadata = {
  title: 'ChessNext',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${inter.variable} antialiased bg-neutral-900 text-white`}
      >
        <Providers>
          <RecoilProvider>
            <Toaster />
            {children}
          </RecoilProvider>
        </Providers>
      </body>
    </html>
  );
}
